name: Trigger auto deployment for fasdfasdcasdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/fasdfasdcasdf-AutoDeployTrigger-9f8badd0-d712-4c0a-9b1b-9ae757357f49.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FASDFASDCASDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASDFASDCASDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASDFASDCASDF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.FASDFASDCASDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASDFASDCASDF_REGISTRY_PASSWORD }}
          containerAppName: fasdfasdcasdf
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/fasdfasdcasdf:${{ github.sha }}
          dockerfilePath: Dockerfile


