name: Trigger auto deployment for fsadfasdfasdfasdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fsadfasdfasdfasdf-AutoDeployTrigger-4b61e222-973f-46eb-8ea4-611972cfe91c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FSADFASDFASDFASDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FSADFASDFASDFASDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FSADFASDFASDFASDF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.FSADFASDFASDFASDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FSADFASDFASDFASDF_REGISTRY_PASSWORD }}
          containerAppName: fsadfasdfasdfasdf
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/fsadfasdfasdfasdf:${{ github.sha }}
          


