name: Trigger auto deployment for tmtest-testrepo-wlp-docker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tmtest-testrepo-wlp-docker-AutoDeployTrigger-9ebe3ccb-05a7-4979-b163-c4be7ca3ec36.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTTESTREPOWLPDOCKER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTTESTREPOWLPDOCKER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTTESTREPOWLPDOCKER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: index.docker.io
          registryUsername: ${{ secrets.TMTESTTESTREPOWLPDOCKER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTTESTREPOWLPDOCKER_REGISTRY_PASSWORD }}
          containerAppName: tmtest-testrepo-wlp-docker
          resourceGroup: tmauldin-test
          imageToBuild: index.docker.io/tmtest-testrepo-wlp-docker:${{ github.sha }}
          


