name: Trigger auto deployment for tmtest-python-wlp-docker2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tmtest-python-wlp-docker2-AutoDeployTrigger-c4f44727-1967-4414-b939-4eb53a495e4e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTPYTHONWLPDOCKER2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTPYTHONWLPDOCKER2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTPYTHONWLPDOCKER2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: index.docker.io
          registryUsername: ${{ secrets.TMTESTPYTHONWLPDOCKER2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTPYTHONWLPDOCKER2_REGISTRY_PASSWORD }}
          containerAppName: tmtest-python-wlp-docker2
          resourceGroup: tmauldin-test
          imageToBuild: index.docker.io/tmtest-python-wlp-docker2:${{ github.sha }}
          


