name: Trigger auto deployment for tmtest-s2c-334

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tmtest-s2c-334-AutoDeployTrigger-4405ea72-4c8c-4840-b1ac-63896187ca52.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TMTESTS2C334_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TMTESTS2C334_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TMTESTS2C334_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: index.docker.io
          registryUsername: ${{ secrets.TMTESTS2C334_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TMTESTS2C334_REGISTRY_PASSWORD }}
          containerAppName: tmtest-s2c-334
          resourceGroup: tmauldin-test
          imageToBuild: index.docker.io/tmtest-s2c-334:${{ github.sha }}
          


